### ISSUE TITLE
Typo in documentation - install part.

### ISSUE THREAD

**Issue by hpiedcoq** [sowdust/tafferugli#1]
Hi,

There is an extra comma in the main page of the documentation : 

`# Change DISTRIBUTION to match yours
echo "deb http://downloads.skewed.de/apt DISTRIBUTION main" >> /etc/apt/sources.list
apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
apt update
apt install python3-graph-tool, python3-cairo`

This leads to some difficulties to install graph tools.

Thanks for this beautiful tool!

**Comment by sowdust** [comment]
Thanks! : )
