### ISSUE TITLE
how to start production mode?

### ISSUE THREAD

**Issue by AntoninHL** [sowdust/tafferugli#10]
Hi,

how to start on production mode instead of development?

Thanks a lot!

A.

**Comment by sowdust** [comment]
Hi, to activate production mode, set DEBUG = False in settings.py
To select the interface in which to listen, launch the runserver command this way: python manage.py runserver IP:PORT (0.0.0.0 to listen an all interfaces).
However, I strongly advise you to refer to the django docs before taking the above approach: https://docs.djangoproject.com/en/3.1/howto/deployment/
