### ISSUE TITLE
Tweepy error

### ISSUE THREAD

**Issue by N3k0t-dev** [sowdust/tafferugli#11]
Hello, i tried to use tafferugli but every time i launch the streamers, in the command line, i can see the following error messages and i didn't have back any valid results.  

The error is the following:
**Tweepy error
[{'code': 144, 'message': 'No status found with that ID.'}]**

Can someone please help me?

**Comment by sowdust** [comment]
Hi, can you please post the full trace of the error?

**Comment by N3k0t-dev** [comment]
Sorry but thi is the only messege that the pyton script _manage.py process_tasks_ give back. There is somethink i can do to obtain more info?

**Comment by sowdust** [comment]
Ok, let's first try to see where the error comes from; it looks like it is not from the streaming process.
Please try to process the different queues (metrics, operations and streamers) separately, to see which one causes the error:
```
python manage.py process_tasks --queue=streamers-queue
python manage.py process_tasks --queue operations
python manage.py process_tasks --queue metrics-computation
```
If it is the "metrics" or "operations" queues that cause the error, please see which kind of metrics or operations are running and I will have a look at their code.

**Comment by sowdust** [comment]
sorry, another thing: please make sure you are working on the latest version; see https://doc.tafferugli.io/install/#upgrade on how to upgrade

**Comment by N3k0t-dev** [comment]
Hi @sowdust, first of all thank you for your support. I tried everithig you said to me, but i can see the same error. Actually i can say to you tha the error is generated from _python manage.py process_tasks --queue=streamers-queue_ as you can see in the following screenshot.
The others python processes doesn't have any error mesages

![image](https://user-images.githubusercontent.com/6221248/101962189-c60d4f80-3c0b-11eb-9fad-0db5aeedf855.png)

**Comment by sowdust** [comment]
I am sorry but I am not able to reproduce the error in any way. 
I have added some error details so that the tweet ID should be printed.
Please make sure to
1) upgrade to the most recent version https://doc.tafferugli.io/install/#upgrade
2) make sure your API key settings are correct.

**Comment by HA016-33** [comment]
Here having the same Issue, and i have all updated and correct ID. I think the problem is that i have 2 campaigns with the same name but i can delete them

**Comment by SrJok3s** [comment]
Hi! I had the same issue, i have solved deleting the campaing trought de DB  and creating it again.
