### ISSUE TITLE
oopsie whoopsie

### ISSUE THREAD

**Issue by VVX7** [sowdust/tafferugli#2]
https://github.com/sowdust/tafferugli/blob/6082ff1d888ff57c4ac8af68bdb7ce75980e095f/tafferugli/settings.py#L25

**Comment by sowdust** [comment]
thanks for noticing, but that key is a default secret key used by Django for some things. In case of tafferugli, only to generate anti  CSRF tokens. The demo application uses a different key, but I have to add a line to the docs that warns users to change their own in case they want to publish the application.
