### ISSUE TITLE
The above exception (no such table: twitter_campaign) 

### ISSUE THREAD

**Issue by iyushaw** [sowdust/tafferugli#5]
This is the error am getting after trying to run it for the first time... I hope someone can guide me to what am doing wrong.

Thanks
```

Request Method: | GET
-- | --
http://127.0.0.1:8000/
3.1.1
OperationalError
no such table: twitter_campaign
/root/tafferugli/env/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py, line 413, in execute
/root/tafferugli/env/bin/python
3.8.2
['/root/tafferugli',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/root/tafferugli/env/lib/python3.8/site-packages',  '/usr/local/lib/python3.8/dist-packages',  '/usr/lib/python3/dist-packages']
Fri, 11 Sep 2020 19:59:16 +0200



```

**Comment by brizzbane** [comment]
I had this [issue](https://github.com/sowdust/tafferugli/issues/4) too.  I'm surprised the install docs didn't include the necessary step.

When following the install instructions, after:

`python manage.py makemigrations`

Do: 

`python manage.py makemigrations twitter`


I just noticed in my issue, there has been another issue added linking to it.  Don't know if above is "correct", or ideal way to do things--but it worked for me.

**Comment by sowdust** [comment]
Thanks for noticing, I have added the line in the documentation
