### ISSUE TITLE
django-taggit

### ISSUE THREAD

**Issue by AlphaQX** [sowdust/tafferugli#7]
**No matching distribution found for django-taggit (from -r requirements.txt (line 12))**
after searching for hours i installed django-taggit using command `apt install python3-django-taggit`

**Comment by sowdust** [comment]
Hi, not sure why you are encountering this problem. I just tried it and am able to install django-taggit using a virtualenv with python 3.7.3 and pip 20.2.3. However, if you were able install the library system wide, just create the virtualenv using the switch `--system-site-packages`  and it should be available in your virtual environment.
